### PR TITLE
[DataGrid] Add ClearSelection method to SelectColumn

### LINKED ISSUE #2163: fix: SelectAll State in DataGrid
# 🐛 Bug Report

BTW: In the Demo Site toggling between settings can also reproduce it.
ccc Screenshot 2024-06-06 134739

After removing rows from datagrid the select all state remains unaffected.

Before Removing content from the collection
AA Screenshot 2024-06-06 132744

After Removing content
bbb Screenshot 2024-06-06 132849

## 💻 Repro or Code Sample

The only way we were able to get it to update was for force calling the setter
```html
<FluentDataGrid TGridItem="CollectionWrapper" Items="@FilteredItems" Pagination="@pagination">
    <SelectColumn @ref="selectColumn" TGridItem="CollectionWrapper" SelectMode="DataGridSelectMode.Multiple" @bind-SelectedItems="@SelectedItems" />
```

```csharp
        private async Task DeleteCollectionsAsync(MouseEventArgs mouseEventArgs)
        {
            var itemstodelete = this.SelectedItems
                .Select(x => x.designCollectionDTO.DesignCollectionUUID)
                .ToArray();

            await this.CollectionService.RemoveDesignCollectionsAsync(itemstodelete, CancellationToken.None);

       
            this.selectColumn.SelectedItems = [];
        }
```
this.selectColumn.SelectedItems  is not recommend BL0005 Component Parameter outside of the component 
```csharp
public class SelectColumn<TGridItem> : ColumnBase<TGridItem>
...
    /// <summary>
    /// Gets or sets the list of selected items.
    /// </summary>
    [Parameter]
    public IEnumerable<TGridItem> SelectedItems
    {
        get => _selectedItems;
        set
        {
            if (_selectedItems != value)
            {
                _selectedItems.Clear();
                _selectedItems.AddRange(value);
            }
        }
    }
```
Note: items and FilteredItems are update in the background followed by an InvokeAsync(StateHasChanged)

## 🤔 Expected Behavior

Provide a manual way to reset/rebuild the Selected Item state.

## 🌍 Your Environment

```
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.7.2" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.7.0" />
```

### PR DESCRIPTION
**Pull request by vnbaaij**
Fix #2163 by adding a `ClearSelection` method to `SelectColumn`

When defining grid like this:
```
<FluentDataGrid TGridItem="CollectionWrapper" Items="@FilteredItems" Pagination="@pagination">
    <SelectColumn @ref="selectColumn" TGridItem="CollectionWrapper" SelectMode="DataGridSelectMode.Multiple" @bind-SelectedItems="@SelectedItems" />
```

Method can be called like this:
```
        private async Task DeleteCollectionsAsync(MouseEventArgs mouseEventArgs)
        {
            var itemstodelete = this.SelectedItems
                .Select(x => x.designCollectionDTO.DesignCollectionUUID)
                .ToArray();

            await this.CollectionService.RemoveDesignCollectionsAsync(itemstodelete, CancellationToken.None);

       
            this.selectColumn.ClearSelection();
        }
```

Prevents BL0005 warning.

### CODE REVIEW

File: src/Core/Components/DataGrid/Columns/SelectColumn.cs [hunk 1]
```diff
@@ -179,6 +179,15 @@ public DataGridSelectMode SelectMode
     [Parameter]
     public override GridSort<TGridItem>? SortBy { get; set; }
 
+    /// <summary>
+    /// Allows to clear the selection.
+    /// </summary>
+    public void ClearSelection()
```
Comment (dvoituron) [inline src/Core/Components/DataGrid/Columns/SelectColumn.cs:185]: Could you create a `ClearSelectionAsync` method, returning `Task.CompletedTask` for now. But better for the future.

**Review by dvoituron — CHANGES_REQUESTED** [review]

**Review by dvoituron — APPROVED** [review]

File: src/Core/Components/DataGrid/Columns/SelectColumn.cs (hunk 1 above)
Comment (vnbaaij) [reply src/Core/Components/DataGrid/Columns/SelectColumn.cs:185]: Done
